<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Raffinert.Expressions</AssemblyName>
    <RootNamespace>Raffinert.Expressions</RootNamespace>
    <Version>1.0.0</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
    <PackageId>Raffinert.Expressions</PackageId>
    <Title>Raffinert.Expressions</Title>
	<Authors>Yevhen Cherkes</Authors>
    <Description>Lightweight composable expression trees for reusable specifications, projections, and LINQ/EF Core query logic.</Description>
    <PackageTags>LINQ;Expressions;ExpressionTree;Specification;Projection;EFCore;Composable;Predicate;Selector</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Raffinert/Raffinert.Expressions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Raffinert/Raffinert.Expressions</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
